### ISSUE TITLE
Gain and Integration Time Not Changing

### ISSUE THREAD

**Issue by 96kaitlinburke** [adafruit/Adafruit_VEML7700#11]
- Board:  Espressif ESP32-S2

- Arduino IDE version: 1.8.13 

I'm trying to run the sample sketch, and I'm just getting 0s for all the values. I noticed that even when I change the gain and integration time with setGain() and setIntegrationTime(), the values printed out by getGain() and getIntegrationTime() are always 1 for the gain and 100ms for the integration time.

**Comment by caternuson** [comment]
Can't recreate this. Running example sketch on a Feather ESP32-S2 and changing these lines:
```cpp
  veml.setGain(VEML7700_GAIN_2);
  veml.setIntegrationTime(VEML7700_IT_400MS);
```

It reports back the values as expected:
![Screenshot from 2022-05-16 17-05-31](https://user-images.githubusercontent.com/8755041/168701609-644d5f1b-a5a4-4782-bbd5-8f391c848c5c.png)

Try updating to latest ESP32 BSP release. There have been a lot of updates to I2C.
