### ISSUE TITLE
Auto lux not working for low light levels

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_VEML7700#18]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=192254

Recreated locally.
![Screenshot from 2022-06-24 09-10-08](https://user-images.githubusercontent.com/8755041/175574882-385e29cf-58b5-4d81-8b71-0947e678b746.png)

**Comment by caternuson** [comment]
Closing. Hopefully fixed with #19.

**Comment by bmtully** [comment]
@caternuson might be related, the autoLux function seems to get stuck when lux drops to zero

If you cover the sensor, then run readLux(VEML_LUX_AUTO), the function won't return until the sensor is uncovered...

**Comment by caternuson** [comment]
@bmtully Please open a new issue for this. Include what sketch you are running and what the Serial Monitor output looks like.
