### ISSUE TITLE
VEML7700 with D1 mini and Tasmota

### ISSUE THREAD

**Issue by 0711smarthome** [adafruit/Adafruit_VEML7700#20]
Is it possible that i can use two ore more VEML7700 with one D1 mini??

**Comment by westado** [comment]
Is it possible that i can use two ore morge VEML7700 with one D1 mini??

**Comment by tyeth** [comment]
Looks like you have one I2C bus on the D1 Mini, as the Lolin i2c connector shares pins 4/5.
https://www.wemos.cc/en/latest/d1/d1_mini.html#pin
You could use an i2c multiplexor which would allow multiple sensors that normally use a single address.
https://forums.adafruit.com/viewtopic.php?f=19&t=167178

**Comment by caternuson** [comment]
Closing since not a library issue. More info on using a muxer:
https://learn.adafruit.com/working-with-multiple-i2c-devices
