### ISSUE TITLE
Reading value stuck

### ISSUE THREAD

**Issue by Hirzi4** [adafruit/Adafruit_VEML7700#24]
Reading the lux value (veml.readLux(VEML_LUX_AUTO)) gets stuck if the sensor is not available.
Is there a solution for this?

I had also the problem with AutoLux after night i get the value 0lx also when the sun is shining.

**Comment by R4sp1** [comment]
Which MCU are you using? 

I've had same issue on ESP32 - when there is no attached sensor, ESP crash every time there is a call to readLux() function. I've solved the issue with simple true/false value in initialization of sensor: 
```
bool check = false;
if(!sensor.begin()){
    check = true;
}
```
and then read the lux value only when this check is false:
```
if(vemlFix == false){
    light = veml.readLux(VEML_LUX_AUTO);
}
```

I will try to look into that in the following weeks.

**Comment by caternuson** [comment]
Using the return value from `sensor.begin()` is the suggested approach for this.

Please open a new issue for the autolux behavior along with example code that cab be used to demonstrate the issue.
