### ISSUE TITLE
Lux value does not exceed 471.85 LUX.

### ISSUE THREAD

**Issue by alexanderbahlk** [adafruit/Adafruit_VEML7700#9]
Hi there,

I would recommend adding the table and context of https://forums.adafruit.com/viewtopic.php?f=19&t=165473&p=840089#p829281 to the wiki.
This would help users using the sensor for real sunlight measurement. 

Thanks

**Comment by caternuson** [comment]
This seems to be same, or at least related, to #1

**Comment by caternuson** [comment]
New Learn page added:
https://learn.adafruit.com/adafruit-veml7700/adjusting-for-different-light-levels
